networks:
  goal-tracker-network:
    driver: bridge
volumes:
  postgres_data:

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - goal-tracker-network
  goal-tracker-api:
    container_name: goal-tracker-api
    build: .
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: npm run start:dev
    volumes:
      - .:/usr/src/app  
      -  /usr/src/app/node_modules
    networks: 
      - goal-tracker-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - goal-tracker-network
